import { createContext, useContext, useEffect, useMemo, useState } from "react";

const UIContext = createContext(null);

const LANGUAGE_KEY = "kilimo_language";
const THEME_KEY = "kilimo_theme";
const ALLOWED_LANGUAGES = ["en", "sw", "fr"];
const ALLOWED_THEMES = ["light", "dark"];

const getInitialTheme = () => {
  if (typeof window === "undefined") return "light";
  const stored = localStorage.getItem(THEME_KEY);
  if (stored === "light" || stored === "dark") {
    return stored;
  }
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
};

const translations = {
  en: {
    navPredict: "Predict",
    navDashboard: "Dashboard",
    navSettings: "Settings",
    navLogout: "Logout",
    navLanguage: "Language",
    navTheme: "Theme",
    langEnglish: "English",
    langSwahili: "Kiswahili",
    langFrench: "French",
    themeLight: "Light",
    themeDark: "Dark",
    loginTitle: "Login",
    loginSubtitle: "Access your maize prediction workspace.",
    username: "Username",
    password: "Password",
    loginButton: "Login",
    authenticating: "Authenticating...",
    noAccount: "No account?",
    register: "Register",
    registerTitle: "Register",
    registerSubtitle: "Create your secure Kilimo Logic account.",
    email: "Email",
    passwordHint: "Password (min 8 chars)",
    confirmPassword: "Confirm Password",
    creatingAccount: "Creating account...",
    alreadyRegistered: "Already registered?",
    maizePredictionTitle: "Maize Yield Prediction",
    maizePredictionNote: "Weather fields are fetched in the background during prediction for secure API key handling.",
    predictionResult: "Prediction Result",
    pleaseWait: "Please wait...",
    soilType: "Soil Type",
    irrigation: "Irrigation",
    fertilizerUsed: "Fertilizer Used",
    irrigationUsedLabel: "Irrigation Used",
    fertilizerAppliedLabel: "Fertilizer Applied",
    phaseLabel: "Phase",
    phaseGerminationTitle: "Germination Phase",
    phaseVegetativeTitle: "Vegetative Phase",
    phaseFloweringTitle: "Flowering Phase",
    phaseGrainFillingTitle: "Grain Filling Phase",
    phaseMaturityTitle: "Maturity Phase",
    daysOfHarvest: "Days of Harvest",
    daysOfHarvestPlaceholder: "e.g. 110",
    yes: "Yes",
    no: "No",
    location: "Location",
    useMyLocation: "Use My Location",
    locationPlaceholder: "e.g. Arusha",
    soilSandy: "Sandy",
    soilLoamy: "Loamy",
    soilClay: "Clay",
    soilSilt: "Silt",
    soilPeaty: "Peaty",
    fetchingWeather: "Fetching Weather...",
    fetchWeather: "Fetch Weather",
    temperature: "Temperature (degC)",
    rainfall: "Rainfall (mm)",
    predicting: "Predicting...",
    predict: "Predict",
    dashboardTitle: "Prediction Dashboard",
    totalPredictions: "Total Predictions",
    mostCommonResult: "Most Common Result",
    latestResult: "Latest Result",
    lastPredictionDate: "Last Prediction Date",
    resultDistribution: "Result Distribution",
    predictionTrend: "Prediction Trend",
    lineChartXAxis: "Date",
    lineChartYAxis: "Number of Predictions",
    lineChartTotal: "Total",
    resultHigh: "High",
    resultMedium: "Medium",
    resultLow: "Low",
    recommendationsTitle: "Recommendations",
    recommendLow1: "Increase fertilizer use, especially during vegetative and flowering stages.",
    recommendLow2: "Improve irrigation consistency.",
    recommendLow3: "Check soil quality and nutrients.",
    recommendLow4: "Monitor and control pests and diseases.",
    recommendMedium1: "Optimize fertilizer timing, especially at flowering stage.",
    recommendMedium2: "Ensure proper irrigation during key growth stages.",
    recommendMedium3: "Monitor crop health regularly.",
    recommendMedium4: "Improve farm management practices.",
    recommendHigh1: "Maintain current farming practices.",
    recommendHigh2: "Avoid overuse of fertilizer.",
    recommendHigh3: "Focus on harvesting and storage.",
    recommendHigh4: "Plan for market selling to maximize profit.",
    resultsBySoilType: "Results by Soil Type",
    lastTenPredictions: "Last 10 Predictions",
    date: "Date",
    soil: "Soil",
    result: "Result",
    loadingAnalytics: "Loading analytics...",
    noAnalytics: "No analytics available.",
    toastWelcome: "Welcome back to Kilimo Logic",
    toastLoginFailed: "Login failed",
    toastAccountCreated: "Account created. Login to continue.",
    toastRegisterFailed: "Registration failed",
    toastSessionExpired: "Session expired. Please login again.",
    toastEnterLocation: "Enter a location first.",
    toastWeatherLoaded: "Weather data loaded",
    toastWeatherFailed: "Unable to fetch weather",
    toastPredictionSaved: "Prediction completed and saved",
    toastPredictionFailed: "Prediction failed. Verify weather data is fetched.",
    toastDashboardFailed: "Unable to load dashboard analytics",
    welcome: "Welcome",
    welcomeGreeting: "Welcome",
    settingsTitle: "Settings",
    settingsSubtitle: "Manage account details and simple preferences.",
    settingsProfileTitle: "Profile",
    settingsEdit: "Edit",
    settingsFirstName: "First Name",
    settingsLastName: "Last Name",
    settingsCancel: "Cancel",
    settingsSaving: "Saving...",
    settingsSaveProfile: "Save Profile",
    settingsChangePassword: "Change Password",
    settingsCurrentPassword: "Current password",
    settingsNewPassword: "New password (min 8 chars)",
    settingsConfirmNewPassword: "Confirm new password",
    settingsUpdatePassword: "Update Password",
    settingsSimpleSystemSettings: "Simple System Settings",
    settingsSwitchToLight: "Switch to Light",
    settingsSwitchToDark: "Switch to Dark",
    settingsEnableNotifications: "Enable Notifications",
    settingsToastLoadFailed: "Unable to load settings",
    settingsToastNoProfileChanges: "No profile changes to save",
    settingsToastProfileUpdateFailed: "Failed to update profile",
    settingsToastProfileUpdated: "Profile updated successfully",
    settingsToastUsernameChanged: "Username changed. Login again later to refresh token claims.",
    settingsToastFillPasswordFields: "Fill all password fields",
    settingsToastPasswordUpdateFailed: "Failed to change password",
    settingsToastPasswordUpdated: "Password changed successfully",
    settingsConfirmUsernameChange: "Changing username may require re-login. Continue?",
    settingsConfirmPasswordChange: "Are you sure you want to change your password?",
    passwordStrength: "Password strength",
    passwordStrength0: "Very weak",
    passwordStrength1: "Weak",
    passwordStrength2: "Fair",
    passwordStrength3: "Strong",
    passwordStrength4: "Very strong",
  },
  sw: {
    navPredict: "Tabiri",
    navDashboard: "Dashibodi",
    navSettings: "Mipangilio",
    navLogout: "Toka",
    navLanguage: "Lugha",
    navTheme: "Mandhari",
    langEnglish: "Kiingereza",
    langSwahili: "Kiswahili",
    langFrench: "Kifaransa",
    themeLight: "Mwanga",
    themeDark: "Giza",
    loginTitle: "Ingia",
    loginSubtitle: "Fikia eneo lako la utabiri wa mahindi.",
    username: "Jina la mtumiaji",
    password: "Nenosiri",
    loginButton: "Ingia",
    authenticating: "Inathibitisha...",
    noAccount: "Huna akaunti?",
    register: "Jisajili",
    registerTitle: "Jisajili",
    registerSubtitle: "Fungua akaunti salama ya Kilimo Logic.",
    email: "Barua pepe",
    passwordHint: "Nenosiri (angalau herufi 8)",
    confirmPassword: "Thibitisha Nenosiri",
    creatingAccount: "Inatengeneza akaunti...",
    alreadyRegistered: "Tayari umesajiliwa?",
    maizePredictionTitle: "Utabiri wa Mavuno ya Mahindi",
    predictionResult: "Matokeo ya Utabiri",
    pleaseWait: "Tafadhali subiri...",
    soilType: "Aina ya Udongo",
    irrigation: "Umwagiliaji",
    fertilizerUsed: "Mbolea Imetumika",
    irrigationUsedLabel: "Umwagiliaji Umetumika",
    fertilizerAppliedLabel: "Mbolea Imewekwa",
    phaseLabel: "Hatua",
    phaseGerminationTitle: "Hatua ya Uotaji",
    phaseVegetativeTitle: "Hatua ya Ukuaji wa Majani",
    phaseFloweringTitle: "Hatua ya Maua",
    phaseGrainFillingTitle: "Hatua ya Kujaza Punje",
    phaseMaturityTitle: "Hatua ya Kukomaa",
    daysOfHarvest: "Siku za Mavuno",
    daysOfHarvestPlaceholder: "mf. 110",
    yes: "Ndiyo",
    no: "Hapana",
    location: "Mahali",
    useMyLocation: "Tumia Mahali Pangu",
    locationPlaceholder: "mf. Arusha",
    soilSandy: "Mchanga",
    soilLoamy: "Tifutifu",
    soilClay: "Mfinyanzi",
    soilSilt: "Tini",
    soilPeaty: "Tifu",
    fetchingWeather: "Inachukua hali ya hewa...",
    fetchWeather: "Chukua Hali ya Hewa",
    temperature: "Joto (degC)",
    rainfall: "Mvua (mm)",
    predicting: "Inatabiri...",
    predict: "Tabiri",
    dashboardTitle: "Dashibodi ya Utabiri",
    totalPredictions: "Jumla ya Utabiri",
    mostCommonResult: "Matokeo Yanayotokea Zaidi",
    latestResult: "Matokeo ya Hivi Karibuni",
    lastPredictionDate: "Tarehe ya Mwisho ya Utabiri",
    resultDistribution: "Mgawanyo wa Matokeo",
    predictionTrend: "Mwelekeo wa Utabiri",
    lineChartXAxis: "Tarehe",
    lineChartYAxis: "Idadi ya Utabiri",
    lineChartTotal: "Jumla",
    resultHigh: "Juu",
    resultMedium: "Wastani",
    resultLow: "Chini",
    recommendationsTitle: "Mapendekezo",
    recommendLow1: "Ongeza matumizi ya mbolea, hasa wakati wa hatua za vegetative na flowering.",
    recommendLow2: "Boresha uthabiti wa umwagiliaji.",
    recommendLow3: "Kagua ubora wa udongo na virutubisho.",
    recommendLow4: "Fuatilia na dhibiti wadudu na magonjwa.",
    recommendMedium1: "Boresha muda wa matumizi ya mbolea, hasa hatua ya flowering.",
    recommendMedium2: "Hakikisha umwagiliaji sahihi katika hatua muhimu za ukuaji.",
    recommendMedium3: "Fuatilia afya ya mazao mara kwa mara.",
    recommendMedium4: "Boresha mbinu za usimamizi wa shamba.",
    recommendHigh1: "Dumisha mbinu za sasa za kilimo.",
    recommendHigh2: "Epuka matumizi kupita kiasi ya mbolea.",
    recommendHigh3: "Zingatia uvunaji na uhifadhi.",
    recommendHigh4: "Panga masoko ya kuuza ili kuongeza faida.",
    resultsBySoilType: "Matokeo kwa Aina ya Udongo",
    lastTenPredictions: "Utabiri 10 za Mwisho",
    date: "Tarehe",
    soil: "Udongo",
    result: "Matokeo",
    loadingAnalytics: "Inapakia takwimu...",
    noAnalytics: "Hakuna takwimu zilizopo.",
    toastWelcome: "Karibu tena Kilimo Logic",
    toastLoginFailed: "Kuingia kumeshindikana",
    toastAccountCreated: "Akaunti imeundwa. Ingia kuendelea.",
    toastRegisterFailed: "Usajili umeshindikana",
    toastSessionExpired: "Muda wa kikao umeisha. Tafadhali ingia tena.",
    toastEnterLocation: "Weka mahali kwanza.",
    toastWeatherLoaded: "Taarifa za hali ya hewa zimepatikana",
    toastWeatherFailed: "Imeshindikana kupata hali ya hewa",
    toastPredictionSaved: "Utabiri umekamilika na kuhifadhiwa",
    toastPredictionFailed: "Utabiri umeshindikana. Hakikisha hali ya hewa imechukuliwa.",
    toastDashboardFailed: "Imeshindikana kupakia takwimu za dashibodi",
    welcome: "Karibu",
    welcomeGreeting: "Karibu",
    settingsTitle: "Mipangilio",
    settingsSubtitle: "Dhibiti taarifa za akaunti na mapendeleo rahisi.",
    settingsProfileTitle: "Wasifu",
    settingsEdit: "Hariri",
    settingsFirstName: "Jina la Kwanza",
    settingsLastName: "Jina la Mwisho",
    settingsCancel: "Ghairi",
    settingsSaving: "Inahifadhi...",
    settingsSaveProfile: "Hifadhi Wasifu",
    settingsChangePassword: "Badilisha Nenosiri",
    settingsCurrentPassword: "Nenosiri la sasa",
    settingsNewPassword: "Nenosiri jipya (angalau herufi 8)",
    settingsConfirmNewPassword: "Thibitisha nenosiri jipya",
    settingsUpdatePassword: "Sasisha Nenosiri",
    settingsSimpleSystemSettings: "Mipangilio Rahisi ya Mfumo",
    settingsSwitchToLight: "Badili kwenda Mwanga",
    settingsSwitchToDark: "Badili kwenda Giza",
    settingsEnableNotifications: "Washa Arifa",
    settingsToastLoadFailed: "Imeshindikana kupakia mipangilio",
    settingsToastNoProfileChanges: "Hakuna mabadiliko ya wasifu ya kuhifadhi",
    settingsToastProfileUpdateFailed: "Imeshindikana kusasisha wasifu",
    settingsToastProfileUpdated: "Wasifu umesasishwa kwa mafanikio",
    settingsToastUsernameChanged: "Jina la mtumiaji limebadilishwa. Ingia tena baadaye kusasisha tokeni.",
    settingsToastFillPasswordFields: "Jaza sehemu zote za nenosiri",
    settingsToastPasswordUpdateFailed: "Imeshindikana kubadilisha nenosiri",
    settingsToastPasswordUpdated: "Nenosiri limebadilishwa kwa mafanikio",
    settingsConfirmUsernameChange: "Kubadilisha jina la mtumiaji kunaweza kuhitaji kuingia tena. Endelea?",
    settingsConfirmPasswordChange: "Una uhakika unataka kubadilisha nenosiri lako?",
    passwordStrength: "Nguvu ya nenosiri",
    passwordStrength0: "Dhaifu sana",
    passwordStrength1: "Dhaifu",
    passwordStrength2: "Wastani",
    passwordStrength3: "Imara",
    passwordStrength4: "Imara sana",
  },
  fr: {
    navPredict: "Predire",
    navDashboard: "Tableau de bord",
    navSettings: "Parametres",
    navLogout: "Deconnexion",
    navLanguage: "Langue",
    navTheme: "Theme",
    langEnglish: "Anglais",
    langSwahili: "Swahili",
    langFrench: "Francais",
    themeLight: "Clair",
    themeDark: "Sombre",
    loginTitle: "Connexion",
    loginSubtitle: "Accedez a votre espace de prediction du mais.",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    loginButton: "Connexion",
    authenticating: "Authentification...",
    noAccount: "Pas de compte ?",
    register: "Inscription",
    registerTitle: "Inscription",
    registerSubtitle: "Creez votre compte securise Kilimo Logic.",
    email: "E-mail",
    passwordHint: "Mot de passe (min 8 caracteres)",
    confirmPassword: "Confirmer le Mot de Passe",
    creatingAccount: "Creation du compte...",
    alreadyRegistered: "Deja inscrit ?",
    maizePredictionTitle: "Prediction du Rendement du Mais",
    maizePredictionNote: "Les champs meteo sont recuperes en arriere-plan pendant la prediction pour securiser la cle API.",
    predictionResult: "Resultat de Prediction",
    pleaseWait: "Veuillez patienter...",
    soilType: "Type de Sol",
    irrigation: "Irrigation",
    fertilizerUsed: "Engrais Utilise",
    irrigationUsedLabel: "Irrigation Utilisee",
    fertilizerAppliedLabel: "Engrais Applique",
    phaseLabel: "Phase",
    phaseGerminationTitle: "Phase de Germination",
    phaseVegetativeTitle: "Phase Vegetative",
    phaseFloweringTitle: "Phase de Floraison",
    phaseGrainFillingTitle: "Phase de Remplissage des Grains",
    phaseMaturityTitle: "Phase de Maturite",
    daysOfHarvest: "Jours de Recolte",
    daysOfHarvestPlaceholder: "ex. 110",
    yes: "Oui",
    no: "Non",
    location: "Lieu",
    useMyLocation: "Utiliser Ma Position",
    locationPlaceholder: "ex. Arusha",
    soilSandy: "Sableux",
    soilLoamy: "Limoneux",
    soilClay: "Argileux",
    soilSilt: "Silteux",
    soilPeaty: "Tourbeux",
    fetchingWeather: "Recuperation meteo...",
    fetchWeather: "Recuperer la Meteo",
    temperature: "Temperature (degC)",
    rainfall: "Pluie (mm)",
    predicting: "Prediction...",
    predict: "Predire",
    dashboardTitle: "Tableau de Bord des Predictions",
    totalPredictions: "Total des Predictions",
    mostCommonResult: "Resultat le Plus Frequent",
    latestResult: "Dernier Resultat",
    lastPredictionDate: "Date de Derniere Prediction",
    resultDistribution: "Distribution des Resultats",
    predictionTrend: "Tendance des Predictions",
    lineChartXAxis: "Date",
    lineChartYAxis: "Nombre de Predictions",
    lineChartTotal: "Total",
    resultHigh: "Eleve",
    resultMedium: "Moyen",
    resultLow: "Faible",
    recommendationsTitle: "Recommandations",
    recommendLow1: "Augmentez l'utilisation d'engrais, surtout pendant les stades vegetatif et floraison.",
    recommendLow2: "Ameliorez la regularite de l'irrigation.",
    recommendLow3: "Verifiez la qualite du sol et les nutriments.",
    recommendLow4: "Surveillez et controlez les ravageurs et les maladies.",
    recommendMedium1: "Optimisez le calendrier de fertilisation, surtout au stade de floraison.",
    recommendMedium2: "Assurez une irrigation correcte pendant les stades cles de croissance.",
    recommendMedium3: "Surveillez regulierement la sante des cultures.",
    recommendMedium4: "Ameliorez les pratiques de gestion de l'exploitation.",
    recommendHigh1: "Maintenez les pratiques agricoles actuelles.",
    recommendHigh2: "Evitez la surutilisation d'engrais.",
    recommendHigh3: "Concentrez-vous sur la recolte et le stockage.",
    recommendHigh4: "Planifiez la vente sur le marche pour maximiser le profit.",
    resultsBySoilType: "Resultats par Type de Sol",
    lastTenPredictions: "10 Dernieres Predictions",
    date: "Date",
    soil: "Sol",
    result: "Resultat",
    loadingAnalytics: "Chargement des analyses...",
    noAnalytics: "Aucune analyse disponible.",
    toastWelcome: "Bon retour sur Kilimo Logic",
    toastLoginFailed: "Echec de connexion",
    toastAccountCreated: "Compte cree. Connectez-vous pour continuer.",
    toastRegisterFailed: "Echec de l'inscription",
    toastSessionExpired: "Session expiree. Veuillez vous reconnecter.",
    toastEnterLocation: "Entrez d'abord un lieu.",
    toastWeatherLoaded: "Donnees meteo chargees",
    toastWeatherFailed: "Impossible de recuperer la meteo",
    toastPredictionSaved: "Prediction terminee et enregistree",
    toastPredictionFailed: "Echec de prediction. Verifiez que la meteo est chargee.",
    toastDashboardFailed: "Impossible de charger les analyses du tableau de bord",
    welcome: "Bienvenue",
    welcomeGreeting: "Bienvenue",
    settingsTitle: "Parametres",
    settingsSubtitle: "Gerez les details du compte et des preferences simples.",
    settingsProfileTitle: "Profil",
    settingsEdit: "Modifier",
    settingsFirstName: "Prenom",
    settingsLastName: "Nom",
    settingsCancel: "Annuler",
    settingsSaving: "Enregistrement...",
    settingsSaveProfile: "Enregistrer le Profil",
    settingsChangePassword: "Changer le Mot de Passe",
    settingsCurrentPassword: "Mot de passe actuel",
    settingsNewPassword: "Nouveau mot de passe (min 8 caracteres)",
    settingsConfirmNewPassword: "Confirmer le nouveau mot de passe",
    settingsUpdatePassword: "Mettre a Jour le Mot de Passe",
    settingsSimpleSystemSettings: "Parametres Systeme Simples",
    settingsSwitchToLight: "Passer en Clair",
    settingsSwitchToDark: "Passer en Sombre",
    settingsEnableNotifications: "Activer les Notifications",
    settingsToastLoadFailed: "Impossible de charger les parametres",
    settingsToastNoProfileChanges: "Aucun changement de profil a enregistrer",
    settingsToastProfileUpdateFailed: "Impossible de mettre a jour le profil",
    settingsToastProfileUpdated: "Profil mis a jour avec succes",
    settingsToastUsernameChanged: "Nom d'utilisateur modifie. Reconnectez-vous plus tard pour rafraichir le jeton.",
    settingsToastFillPasswordFields: "Remplissez tous les champs du mot de passe",
    settingsToastPasswordUpdateFailed: "Impossible de changer le mot de passe",
    settingsToastPasswordUpdated: "Mot de passe modifie avec succes",
    settingsConfirmUsernameChange: "Changer le nom d'utilisateur peut necessiter une reconnexion. Continuer ?",
    settingsConfirmPasswordChange: "Voulez-vous vraiment changer votre mot de passe ?",
    passwordStrength: "Solidite du mot de passe",
    passwordStrength0: "Tres faible",
    passwordStrength1: "Faible",
    passwordStrength2: "Moyen",
    passwordStrength3: "Fort",
    passwordStrength4: "Tres fort",
  },
};

export const UIProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem(LANGUAGE_KEY) || "en";
    return ALLOWED_LANGUAGES.includes(saved) ? saved : "en";
  });
  const [theme, setThemeState] = useState(() => {
    const initial = getInitialTheme();
    return ALLOWED_THEMES.includes(initial) ? initial : "light";
  });

  const setLanguage = (nextLanguage) => {
    if (ALLOWED_LANGUAGES.includes(nextLanguage)) {
      setLanguageState(nextLanguage);
    }
  };

  const setTheme = (nextTheme) => {
    if (ALLOWED_THEMES.includes(nextTheme)) {
      setThemeState(nextTheme);
    }
  };

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem(THEME_KEY, theme);
    document.documentElement.classList.toggle("dark", theme === "dark");
    document.body.classList.toggle("dark", theme === "dark");
  }, [theme]);

  const toggleTheme = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      theme,
      setTheme,
      toggleTheme,
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language, theme]
  );

  return <UIContext.Provider value={value}>{children}</UIContext.Provider>;
};

export const useUI = () => {
  const context = useContext(UIContext);
  if (!context) {
    throw new Error("useUI must be used within UIProvider");
  }
  return context;
};
